elfin_robot_ip: 10.20.60.88
elfin_servo_port: 8892
elfin_cds_data_port: 8893
elfin_tcp_cmd_port: 10003
elfin_tcp_state_port: 10005
servoj_time: 0.025
servoj_lookahread_time: 0.2

elfin:
    slave_no: [1, 2, 3, 4, 5, 6]
    joint_names: [elfin_joint1, elfin_joint2, elfin_joint3, elfin_joint4, elfin_joint5, elfin_joint6]
